server:
  port: 8082

spring:
  application:
    name: notification
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672

  datasource:
    name: notificationdb
    url: jdbc:mysql://localhost:3306/notificationdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key
